---
- name: Disable SElinux
  selinux: state=disabled

- name: Disable firewalls
  service: name=firewalld state=stopped

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Add group "die"
  group: name=die

- name: Add user "die"
  user: name=die group=die home=/srv/dieroot/

- name: Install dev tools (yum)
  yum: name={{ item }} state=installed
  with_items: "{{common.devtools}}"

- name: Install dev tools (npm)
  npm: name={{ item }} global=yes
  with_items: "{{common.npmdevtools}}"