---
- name: Create Docroot ({{ name }})
  file: path=/srv/dieroot/{{ name }} state=directory

- name: Create nginx vhost definition ({{ name }})
  template:
    src: vhost.j2
    dest: /etc/nginx/conf.d/{{ name }}.vhost.conf
  notify: restart nginx